services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_DB: criminalidade_db
      POSTGRES_USER: criminalidade_user
      POSTGRES_PASSWORD: criminalidade_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - oracle_net
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - oracle_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  oracle_net:
    external: true