[pytest]

testpaths =
    tests

pythonpath =
    .
    src

addopts =
    --strict-markers
    -vv
    -ra
    --color=yes
    --disable-warnings
    -n auto
    --dist=loadfile

    --html=test_report/relatorio-testes.html
    --self-contained-html

    --junitxml=test_report/junit.xml

markers =
    serial: marcador para testes que nao podem rodar em paralelo (AppTest)
    integracao: testes que exigem Postgres real via Testcontainers (Docker)

norecursedirs =
    venv
    .git
    __pycache__
    test_report
