[pytest]

testpaths =
    tests

pythonpath =
    .
    src

addopts =
    --strict-markers
    -vv
    -ra
    --color=yes
    --disable-warnings

    --html=test_report/relatorio-testes.html
    --self-contained-html

    --junitxml=test_report/junit.xml

    --cov=analysis
    --cov=api
    --cov=config
    --cov=database
    --cov=domain
    --cov=ingestion
    --cov=processing
    --cov=src
    --cov=util

    --cov-report=term-missing
    --cov-report=html:test_report/coverage
    --cov-report=xml:test_report/coverage.xml

    --cov-fail-under=95

norecursedirs =
    venv
    .git
    __pycache__
    test_report